### ISSUE TITLE
SGPlatform/SGPlatform.h file not found

### ISSUE THREAD

**Issue by tommyz** [libobjc/SGPlayer#1]
SGPlatform/SGPlatform.h file not found

**Comment by libobjc** [comment]
两种情况
1.如果是使用git clone命令下载的项目，请确认是否在git目录中执行‘git submodule update --init --recursive’来安装子模块。
2.如果是使用Download ZIP下载的项目，请下载项目[https://github.com/libobjc/SGPlatform](SGPlatform)并放在Vendors目录下。

如果没有解决，请参看README.md中的编译步骤对照问题。

**Comment by libobjc** [comment]
两种情况
1.如果是使用git clone命令下载的项目，请确认是否在git目录中执行‘git submodule update --init --recursive’来安装子模块。
2.如果是使用Download ZIP下载的项目，请下载项目[SGPlatform](https://github.com/libobjc/SGPlatform)并放在Vendors目录下。

如果没有解决，请参看README.md中的编译步骤对照问题。

**Comment by fukemy** [comment]
english plzz

**Comment by kylelamx** [comment]
He said
> There are 2 cases
> 1. if you used `git clone` to download the project, please make sure you run `git submodule update --init --recursive` on your git directory to install the submodule, or
> 2. if you download with that green `Download ZIP` button, please download the [SGPlatform](https://github.com/libobjc/SGPlatform) project and put that under the `Vendors` folder.
> if that doesn't work, try the Build Instructions listed in README.md

btw, I have no luck following either 1 or 2 :(
