### ISSUE TITLE
请问文档里的图片使用什么软件做的

### ISSUE THREAD

**Issue by wangzz** [libobjc/SGPlayer#10]
你好，请问文档里的图片是使用什么软件做的？比如这个图片https://camo.githubusercontent.com/b47d8d4851d70c79331a26653d6b325dc7d676ba/68747470733a2f2f636f64696e672e6e65742f752f30783031303130312f702f7265736f757263652d7075626c69632f6769742f7261772f6d61737465722f5347506c617965722f53474646506c617965722d7468726561642e6a706567

**Comment by libobjc** [comment]
Keynote
