### ISSUE TITLE
支持conact 格式 视频吗

### ISSUE THREAD

**Issue by yang0000meng** [libobjc/SGPlayer#105]
支持conact 格式 视频吗  ffmpeg 是支持的
不知道SGPlayer 是否支持 
格式如下
file://***/abc.concat
abc.concat 文件内容如下
ffconcat version 1.0
file http://www.baidu.com/1.mp4
duration 300
file http://www.baidu.com/2.mp4
duration 300

**Comment by libobjc** [comment]
对 SGPlayer 是透明的，FFmpeg 编译时支持对应协议即可
