### ISSUE TITLE
后台切换视频程序崩溃

### ISSUE THREAD

**Issue by chaocharleswang** [libobjc/SGPlayer#106]
Crash位置 SGVideoRenderer.m

[commandBuffer presentDrawable:drawable];

-[_MTLCommandBuffer presentDrawable:]:400: failed assertion `drawable must not be nil.'

**Comment by chaocharleswang** [comment]
[https://github.com/mpv-player/mpv/pull/6903#issue-313095457](url)

**Comment by chaocharleswang** [comment]
#107 
Fixed it by checking the size of CAMetalLayer

**Comment by libobjc** [comment]
👍
