### ISSUE TITLE
'avformat.h' file not found

### ISSUE THREAD

**Issue by ywdonga** [libobjc/SGPlayer#129]
运行工程发现报错：
'avformat.h' file not found

![image](https://user-images.githubusercontent.com/16291063/81517611-51b0bc00-935d-11ea-8e41-327b1a83e4fa.png)

**Comment by maulikTeksun** [comment]
I am having same issue. Could you please help us?

**Comment by dalnim** [comment]
Did you run ./build.sh iOS build for FFMpeg?
