### ISSUE TITLE
demo  vr 例子播放 在真机器上面没有画面只有声音,m3u8 真机播放失败

### ISSUE THREAD

**Issue by maopenglin** [libobjc/SGPlayer#2]

**Comment by maopenglin** [comment]
iphone6 ios8.3

**Comment by libobjc** [comment]
demo中没有去掉ATS的限制

**Comment by maopenglin** [comment]
google-help-vr.mp4 真机只有声音 没有画面，模拟器正常

**Comment by maopenglin** [comment]
默认播放，暂停一下在播放，画面和声音 不一致了，网络不好的时候，状态提示没有变，还是playing状态，应该是提示加载中，没有这样的通知  http://ivi.bupt.edu.cn/hls/cctv1hd.m3u8

**Comment by maopenglin** [comment]
http://ivi.bupt.edu.cn/hls/cctv1hd.m3u8  这个地址 硬编码 崩溃

**Comment by libobjc** [comment]
我用ffplay播了一下，这个视频流太卡了，基本属于不可正常观看的状态。且ffplay也会偶发崩溃
其他问题我抽空会看下，建议你加群，方便沟通。
