### ISSUE TITLE
How to play flv segments as a full video?

### ISSUE THREAD

**Issue by fuzhuo** [libobjc/SGPlayer#20]
Some video source split the whole video to many flv segments, I tried merge it to a hls format m3u8 file, but it play failed with Error
"Error Domain=ffmpeg code : -541478725, ffmpeg msg : End of file Code=2 "(null)"

I see MPV provide an "edl protocol" to play segments like edl://f1.flv;f2.flv
Is there any similar solution for SGPlayer?

I tried merge to m3u8 format like below, but seems hls didn't accept flv video codec.
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:400
#EXTINF:348.859,
http://samplesite/f1.flv
#EXTINF:381.301,
http://samplesite/f2.flv
#EXT-X-ENDLIST

**Comment by fuzhuo** [comment]
I implemented this from UI user layer...

**Comment by KouMeanSun** [comment]
你的服务器是什么？你需要一个专门的直播服务器，比如nginx，看下这篇文章。http://www.cnblogs.com/jys509/p/5653720.html。  你可以把他翻译一下。
What's your server ?you need a professional live server,like ngix. look at this blog。http://www.cnblogs.com/jys509/p/5653720.html   。You can translate this.

**Comment by fuzhuo** [comment]
与ffmpeg服务器端没有关系，纯粹播放器
比如用you-get解析B站等视频后得到是几段flv信息和每段时间信息，然后这些片断播放时需要作为一个整体来播放

**Comment by KouMeanSun** [comment]
那就用https://www.vitamio.org 。之前我就用的这个库，倒链的 斗鱼 的直播链接，是可以播放的。我们要做的就是把真正的url丢到播放器里就可以。

**Comment by fuzhuo** [comment]
不必了，已经自己实现了。竟然还带打广告的…
