### ISSUE TITLE
SGFFAudioDecoder类中的reloadAudioOuputInfo方法有笔误

### ISSUE THREAD

**Issue by Chentao981** [libobjc/SGPlayer#22]
- (void)reloadAudioOuputInfo
{
    if ([self.delegate respondsToSelector:@selector(audioDecoder:channelCount:)]) {
        [self.delegate audioDecoder:self samplingRate:&self->_samplingRate];
    }
    if ([self.delegate respondsToSelector:@selector(audioDecoder:samplingRate:)]) {
        [self.delegate audioDecoder:self channelCount:&self->_channelCount];
    }
}
这个方法里的代码是不是应该写成：
- (void)reloadAudioOuputInfo
{
    if ([self.delegate respondsToSelector:@selector(audioDecoder:channelCount:)]) {
        [self.delegate audioDecoder:self channelCount:&self->_channelCount];
    }
    if ([self.delegate respondsToSelector:@selector(audioDecoder:samplingRate:)]) {
        [self.delegate audioDecoder:self samplingRate:&self->_samplingRate];
    }
}

**Comment by libobjc** [comment]
感谢反馈！
