### ISSUE TITLE
拖动进度条 player seekToTime ，但是播放的时候总是比seek的Time 倒退了几秒

### ISSUE THREAD

**Issue by guzhike2012** [libobjc/SGPlayer#29]

**Comment by fuzhuo** [comment]
从代码看，seek是直接用的AVSEEK_FLAG_BACKWARD。然后行为是向前跳转到最近的一个关键帧，和目标跳转进度差距会很大十秒都有可能。看起来只能改代码增加seek调整逻辑，从关键帧开始往后跳帧直到达到目标时间才开始正常播放
av_seek_frame(self->_format_context, -1, ts, AVSEEK_FLAG_BACKWARD);

**Comment by 1011875777** [comment]
@qiudaomao 你好，我也发现了这个问题，你能提交pull request

**Comment by qiudaomao** [comment]
> @qiudaomao 你好，我也发现了这个问题，你能提交pull request

这个改动太大了，难度太高，我已经转mpv或者IJKPlayer了，mpv项目更活跃

**Comment by 1011875777** [comment]
我查看了源码后发现，这个效果其实是作者专门对ffmpeg的seek做了保护控制，如果你不想要可以在SGGLViewController.m中注释掉336到344行的seek time计算方法； 如果还是不能满足你的需求的话就搜索av_seek_frame函数的调用，将AVSEEK_FLAG_BACKWARD修改为AVSEEK_FLAG_ANY，但是这样seek可能会出现花屏。 @qiudaomao @guzhike2012
