### ISSUE TITLE
有个问题请教

### ISSUE THREAD

**Issue by yilongchun** [libobjc/SGPlayer#30]
现在是调用 replaceVideoWithURL 就会自动缓冲，有没有办法来控制 不让他缓冲，比如用手机流量的时候，调用暂停好像也会缓冲，那样不是也废流量

**Comment by libobjc** [comment]
这个建议在业务侧控制，非 WIFI 环境不要 replaceVideoWithURL。

**Comment by yilongchun** [comment]
还有一个问题，在播放的时候用手势滑动返回没有返回到上一个界面，又回到本界面，播放会卡住
