### ISSUE TITLE
iOS/tvOS 11 beta4 ffmpeg crash

### ISSUE THREAD

**Issue by phil-m** [libobjc/SGPlayer#31]
Great library, thanks for all the effort into it!

The ffmpeg player has been working great up until today when I upgraded from iOS & tvOS 11 beta 3 to beta 4. It now crashes on both iOS & tvOS (playing a server ts stream). The only error Xcode gives is 'Thread 1: EXC_BAD_ACCESS (code=2, address=0x194c50ad8)' pointing to main.m, even with 'All Exceptions' breakpoint enabled. 

To double check, I ran the exact same build under beta 3 on iOS & it worked fine, I then upgraded the device to beta 4 & re-ran & it now crashes in the same way the tvOS build does.

A little bit of manual debugging seems to show its crashing when it goes to display the first frame (or around that time), possibly OpenGL/rendering related? Not sure if this is an iOS/tvOS beta issue (that Apple may fix in a future beta), or maybe a change in the api that SGPlayer will need updating to handle perhaps. 

Any ideas/pointers on how to get this working would be really appreciated!
Thanks.

**Comment by skrew** [comment]
In Xcode (beta 4):

- Edit scheme
- Turn off GPU Frame Capture (should be disabled)

BTW I don't know if this project are still active...

**Comment by phil-m** [comment]
Thank you @skrew !! This worked great!

Incase anyone else tries this, make sure you have an actual iOS/tvOS build target selected, not a simulator one, or the option won't show in the edit scheme screen (its on the 'Options' tab, at least in beta4).

I agree this project isn't majorly active, but from previous testing it was the most feature complete ffmpeg compatible lib that worked across iOS & tvOS, & has been working great for me so far, so I hope it remains at least somewhat active.
