### ISSUE TITLE
播放网络视频   使用FFmpeg解码，执行到avformat_find_stream_info一直crash

### ISSUE THREAD

**Issue by xRuby** [libobjc/SGPlayer#33]
根据你的代码制作了静态库，新建工程引入静态库是可以没有问题的，但是加入到现有工程，使用FFmpeng解码，每次执行到avformat_find_stream_info 便crash，视频是没有问题的，是现有工程设置问题？
<img width="704" alt="2017-08-07 6 57 12" src="https://user-images.githubusercontent.com/11939075/29057780-577b5498-7c3f-11e7-8f28-64d3c59ba9c0.png">

<img width="974" alt="59b25b2c-083b-42a3-833d-cf109a64bb16" src="https://user-images.githubusercontent.com/11939075/29057981-7755a358-7c40-11e7-81b4-b8e52f81aa1f.png">

**Comment by libobjc** [comment]
检查一下项目中是否导入了其他基于 FFmpeg 的播放器。应该是你项目中同时存在多个版本的 FFmpeg。

**Comment by xRuby** [comment]
播放本地视频，帧速 怎么感觉慢了几帧，感觉像是慢动作...  是本来就这样还是应该设置什么，求解，上一条报错是之前与环信的SDK冲突

**Comment by xRuby** [comment]
且连续播放几十次之后，状态不能捕获，NSLog 打印的是Playing，实际画面已经停滞。

**Comment by xRuby** [comment]
以上均是FFMpeg格式测试
