### ISSUE TITLE
navigationController pushViewController: animated:后,画面会不动，但是会有声音。

### ISSUE THREAD

**Issue by yyxaf** [libobjc/SGPlayer#34]
控制器A播放视频，然后push一个控制器，再pop回控制器A，视频画面会不动，但是会有声音。
然后加群也加不进。

**Comment by yyxaf** [comment]
push后发现是GLKViewController 不会调用- (void)glkView:(GLKView *)view drawInRect:(CGRect)rect了，不调用的原因不清楚。
解决：把GLKViewController替换为GLKView+CADisplayLink方式，问题解决。

**Comment by chiseller** [comment]
你好，请问可以提供一下解决的demo么，谢谢
