### ISSUE TITLE
Do not play iCloud Url

### ISSUE THREAD

**Issue by veila** [libobjc/SGPlayer#38]
Hi,
I am considering use SGPlayer in my app. But some urls from our server in icloud like google driver, dropbox,... SGPlayer can not play, example this url  "https://doc-0k-0g-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/8o5e04j9vvg4ka137sb1tqskcah4jfjn/1503964800000/10881491144528811151/*/0B3yDNrNFBYlJckxxNlFfZm5DTGs". I test another urls not from icloud very good.
Pls tell me What I am wrong?

**Comment by BigVeila** [comment]
@libobjc why this guy always closed topic. Some errors have not been fixed yet but you have closed
