### ISSUE TITLE
demo运行没有任何问题 能播放任何格式视频  xcode打包出来的framework 播放不了任何视频 报Domain=video codec not found decoder Code=6

### ISSUE THREAD

**Issue by vhikd** [libobjc/SGPlayer#46]
如题

**Comment by chouhanv** [comment]
Undefined symbols for architecture x86_64:
  "_OBJC_IVAR_$_SGFFAVYUVVideoFrame.channel_pixels", referenced from:
      -[SGGLTextureYUV420 updateTextureWithGLFrame:aspect:] in SGPlayer(SGGLTextureYUV420.o)
  "_OBJC_CLASS_$_SGFFAVYUVVideoFrame", referenced from:
      objc-class-ref in SGPlayer(SGGLFrame.o)
  "_OBJC_CLASS_$_SGFFCVYUVVideoFrame", referenced from:
      objc-class-ref in SGPlayer(SGGLFrame.o)
  "_OBJC_CLASS_$_SGFFPlayer", referenced from:
      objc-class-ref in SGPlayer(SGPlayerImp.o)
     (maybe you meant: _OBJC_CLASS_$_SGFFPlayerShell)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chouhanv** [comment]
Undefined symbols for architecture x86_64:
  "_OBJC_IVAR_$_SGFFAVYUVVideoFrame.channel_pixels", referenced from:
      -[SGGLTextureYUV420 updateTextureWithGLFrame:aspect:] in SGPlayer(SGGLTextureYUV420.o)
  "_OBJC_CLASS_$_SGFFAVYUVVideoFrame", referenced from:
      objc-class-ref in SGPlayer(SGGLFrame.o)
  "_OBJC_CLASS_$_SGFFCVYUVVideoFrame", referenced from:
      objc-class-ref in SGPlayer(SGGLFrame.o)
  "_OBJC_CLASS_$_SGFFPlayer", referenced from:
      objc-class-ref in SGPlayer(SGPlayerImp.o)
     (maybe you meant: _OBJC_CLASS_$_SGFFPlayerShell)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by vhikd** [comment]
需要把ffmpeg编译好的库翻到目录里
