### ISSUE TITLE
大神，就目前的计划而言，SGPlayer会继续维护吗？

### ISSUE THREAD

**Issue by LiuDeng** [libobjc/SGPlayer#5]
如题，感谢开发如此好用的库~
祝好~

**Comment by libobjc** [comment]
一定会！

**Comment by LiuDeng** [comment]
多谢大神回复~如果可以希望能加入一些控制层的代码 比如左右滑动可快进快退，左边屏幕上下滑动调整亮度，右侧屏幕滑动调整音量神马的，可以参考下ZFPlayer。期待SGPlayer成为苹果平台播放器首选组件~
祝好~

**Comment by JHCoderLion** [comment]
希望可以参考下ZFPlayer    因为目前而言框架内部的功能还不是很完善
