### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by KKFinger** [libobjc/SGPlayer#50]
demo编译失败  

Undefined symbols for architecture arm64:
  "_OBJC_IVAR_$_SGFFAVYUVVideoFrame.channel_pixels", referenced from:
      -[SGGLTextureYUV420 updateTextureWithGLFrame:aspect:] in SGPlayer(SGGLTextureYUV420.o)
  "_OBJC_CLASS_$_SGFFAVYUVVideoFrame", referenced from:
      objc-class-ref in SGPlayer(SGGLFrame.o)
  "_OBJC_CLASS_$_SGFFCVYUVVideoFrame", referenced from:
      objc-class-ref in SGPlayer(SGGLFrame.o)
  "_OBJC_CLASS_$_SGFFPlayer", referenced from:
      objc-class-ref in SGPlayer(SGPlayerImp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

概率性的编译失败  有时候可以  过一会就又不行了  好诡异

**Comment by huangrun** [comment]
遇到同样问题，请问解决了吗

**Comment by iamvijay** [comment]
Hey, I am facing the same issue, Any solution for this?

**Comment by KKFinger** [comment]
ios、mac、tvos三个版本的ffmpeg库需要对应上，不能将ios版本的ffmpeg库加到mac的target中，否则会出现上述错误
