### ISSUE TITLE
是否支持全景图片的播放

### ISSUE THREAD

**Issue by chiseller** [libobjc/SGPlayer#52]
首先感谢作者，想问下，本项目支持全景图片查看么？

**Comment by icewong** [comment]
我前段时间也在初步使用了，是可以的


原始邮件
发件人:chisellernotifications@github.com
收件人:libobjc/SGPlayerSGPlayer@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2018年1月9日(周二) 10:22
主题:[libobjc/SGPlayer] 是否支持全景图片的播放 (#52)


首先感谢作者，想问下，本项目支持全景图片查看么？

**Comment by chiseller** [comment]
我尝试了一下好像不行。可以说下具体的思路么，谢谢

**Comment by icewong** [comment]
我是直接把[NSURL fileURLWithPath:[[NSBundle mainBundle] pathForResource:@"v_15115153665832" ofType:@“mp4/jpg"]]直接传给他播放的。全景的图片和视频是一样的。


原始邮件
发件人:chisellernotifications@github.com
收件人:libobjc/SGPlayerSGPlayer@noreply.github.com
抄送:BingWangbingw@ion360.com; Commentcomment@noreply.github.com
发送时间:2018年1月9日(周二) 13:46
主题:Re: [libobjc/SGPlayer] 是否支持全景图片的播放 (#52)


我尝试了一下好像不行。可以说下具体的思路么，谢谢

**Comment by chiseller** [comment]
谢谢，我是渲染的在线的图片貌似还是有点问题，图片的颜色好像不对

**Comment by zcb1603999** [comment]
你们的图片渲染出来之后清晰度怎么样？不模糊吗？

**Comment by chiseller** [comment]
颜色渲染出来是有问题的
