### ISSUE TITLE
Can you change GPL license to MIT or BSD?

### ISSUE THREAD

**Issue by chapayGhub** [libobjc/SGPlayer#6]
Hey good work!
GPL license have some issue on iOs platform

http://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement
https://forums.developer.apple.com/thread/18922

Thanks

**Comment by libobjc** [comment]
Hey!
I change license to LGPL. can you?

**Comment by chapayGhub** [comment]
Thanks!
