### ISSUE TITLE
Error Domain=ffmpeg code : -1330794744

### ISSUE THREAD

**Issue by LuohanCC** [libobjc/SGPlayer#65]

**Comment by ko1o** [comment]
> 我把你IOS demo中所有代码拷进我的项目，一直报错： player did error : Error Domain=ffmpeg code : -1330794744, ffmpeg msg : Protocol not found Code=1 "(null)"
> 
> 新建项目，并拷贝代码运行，还是报这个错，只有您的demo中不会出现这个问题。

@LuohanCC 哥们请问你解决了吗？ 我也遇到这个问题了
