### ISSUE TITLE
1，有声音画面不动 2，进度条

### ISSUE THREAD

**Issue by huhuan1992** [libobjc/SGPlayer#67]
有2个问题：
1，设播放vr视频页面为A，另一个页面为B，当A页面VR视频处于播放时，导航push页面B 并暂停视频播放，pop出来后，VR视频只有声音，但画面不动了？
2，拖动播放进度条到某个时间，进度条回弹。

**Comment by WZSlike** [comment]
确实会有问题1这个问题，我也遇到了，希望作者可以看看
