### ISSUE TITLE
Delay in the rtmp url not matching with live

### ISSUE THREAD

**Issue by iamvijay** [libobjc/SGPlayer#68]
Hi, I have implemented Sgplayer and i am using a rtmp url. It is working fine but there is 4 to 5 secs delay in the player video and the live one. I have tried buffer everything but it is not helping to overcome the issue. 

And one more issue is if i go background mode and comeback there is extra 5 secs delay added to the player, So how can i move player to the current timing. I tried enabling background mode too. any solution for this?

**Comment by codeghost666** [comment]
any solution for this problem? I face same issue now.

**Comment by fukemy** [comment]
use https://github.com/Bilibili/ijkplayer

**Comment by iamvijay** [comment]
> use https://github.com/Bilibili/ijkplayer

Is this working properly ? I tried demo it is giving 'libavformat/avformat.h' file not found error

**Comment by fukemy** [comment]
u need to follow his instruction to get ijkplayer

**Comment by fukemy** [comment]
u need config for rtsp/rtmp protocol, i think so
