### ISSUE TITLE
Memory issues on iPhone 5 ,iPhone 5s iOS 9

### ISSUE THREAD

**Issue by duyhungtnn** [libobjc/SGPlayer#7]
Hi libobjc, good work  👍 
I find one issue.
I try SGPlayer today and It works perfectly on my iPhone 6 and iPhone 6s.
But when I install demo app on iPhone 5, 5s iOS 9 and play RTMP url, this app quickly received memory warning and app crashes, only crashes when play RTMP.
I switch to use HLS url, this app play video streaming ok.

**Comment by libobjc** [comment]
Thinks!
I received your issue.
I will try to fix this in 1.0.0.

**Comment by libobjc** [comment]
Thanks!
I received your issue.
I will try to fix this in 1.0.0.

**Comment by khemmachart** [comment]
How is it going?

**Comment by antonz0319** [comment]
Hi @libobjc , thanks for this great media player.
I am also getting memory issue on iPhone 5 (iOS 10.3).
Is there any update for this issue ?
Thanks

**Comment by kirti301290** [comment]
@duyhungtnn @antonz0319 
how to you have integrated in  your app
it working in demo app ,how to integrated to my app 
can not find how to make SGPlayer.framework
Please need some help .
thanks
