### ISSUE TITLE
Thread 8: EXC_BAD_ACCESS (code=EXC_I386_GPFLT) in SGFFFormatContext ( stream->codecpar->codec_type)

### ISSUE THREAD

**Issue by MMichel123123** [libobjc/SGPlayer#70]
Crash before player become ready to play.
Problem with AVMediaType codec_type;

Piece of code: 

        let temp = "rtmp://184.72.239.149/vod/mp4:bigbuckbunny_450.mp4"
        
        self.player = SGPlayer()
        self.player.registerNotificationTarget(self, stateAction: #selector(state1Changed), progressAction:  #selector(stateChanged), playableAction:  #selector(stateChanged))
        self.player.viewTapAction = { sgplayer, view in
            
        }
        
        view.insertSubview(player.view, at: 0)
        
        self.player.decoder = SGPlayerDecoder.byFFmpeg()
        self.player.replaceVideo(with: URL(string: temp)!)
        
        player.play()

**Comment by OsamaMukhtar** [comment]
I am having the same issue. SGPlayer works fine when I create new project and integrate into it. But when I integrate it in my existing project it crashes here. Seems like some kind of conflict of libs or some wrings flags in project settings. please help if someone has fixed it.
