### ISSUE TITLE
can play rtmp url?

### ISSUE THREAD

**Issue by fukemy** [libobjc/SGPlayer#76]

**Comment by desmond0321** [comment]
yes, you can play rtmp like this
normalVideo = [NSURL URLWithString:@"rtmp://xxxx.xxx:1234/asdad"];

**Comment by fukemy** [comment]
thanks you. It's one of best library to me . But i need to config to get faster open rtmp link.
After a short time using your library, i feel it's very great, now I want to ask can I make faster opening  rtmp live url?

Thanks you.

**Comment by fukemy** [comment]
?
