### ISSUE TITLE
'SGPlatform/SGPlatform.h' file not found in Xcode 10.1

### ISSUE THREAD

**Issue by chaocharleswang** [libobjc/SGPlayer#83]
I followed the steps in Readme multiple times.
However, I always got the error.
Frustrated.

**Comment by chaocharleswang** [comment]
I got the error here:

//
//  SGYUVTools.h
//  SGPlayer
//
//  Created by Single on 2017/3/2.
//  Copyright © 2017年 single. All rights reserved.
//

#import <SGPlatform/SGPlatform.h>
#import "pixfmt.h"

....

**Comment by KaoUserName** [comment]
使用了脚本安装，问题依然存在，demo不能运行。
