### ISSUE TITLE
How to control playback speed or customize the frame clock?

### ISSUE THREAD

**Issue by chaocharleswang** [libobjc/SGPlayer#84]
I used ffmpeg decoder to play video track (no audio).

However, I found the playback speed is about 2x slower than normal.

How can I control the playback speed or customize the frame clock to solve the issue?

**Comment by chaocharleswang** [comment]
I did some testing. I tested a video with video track and audio track. By default, it uses audio time clock . The video plays well. However, if I changed to use video time clock, the video plays slower than before.

**Comment by kirti301290** [comment]
@chaocharleswang 
it works in demo app ,how to integrated to my app
can not find how to make SGPlayer.framework
Please need some help .
thanks
