### ISSUE TITLE
进入FFmpeg就崩溃呢？FFmpeg的库没问题啊，从别的demo拖过来的啊

### ISSUE THREAD

**Issue by LJW008** [libobjc/SGPlayer#92]
![f11f4454-f697-4362-b747-b267783000c8](https://user-images.githubusercontent.com/11679563/53168731-4e28fc00-3616-11e9-9403-5fbf75bc7dd0.png)

**Comment by libobjc** [comment]
项目中可能有其它三方库内嵌了 FFmpeg
